dist: focal
language: node_js
node_js:
  - "lts/*"
cache: yarn
env:
  global:
    - APPLICATION_NAME: dimes
cache:
  directories:
    - node_modules
install:
  - yarn install
before_script:
  - if [ ! -d deploy_scripts ]; then git clone https://github.com/RockefellerArchiveCenter/deploy_scripts.git; fi
  - sudo deploy_scripts/substitute_env.sh
script:
  - docker build .
  - CI=false yarn run build
  - yarn test
before_deploy:
  - pip install awscli
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  local_dir: $LOCAL_DIR
  skip_cleanup: true
  on:
    repo: RockefellerArchiveCenter/${APPLICATION_NAME}
    all_branches: true
    condition: TRAVIS_BRANCH =~ ^(development|production)$
  bucket: $AWS_BUCKET_NAME
  region: us-east-1
after_deploy:
  - bash deploy_scripts/containers/invalidate_cloudfront_cache.sh
notifications:
  email: false
