language: node_js
env:
  global:
    - APPLICATION_NAME: dimes
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - yarn install
script:
  - CI=false yarn run build
  - yarn test
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: build
    skip_cleanup: true
    on:
      repo: RockefellerArchiveCenter/${APPLICATION_NAME}
      branch: base
    bucket: $AWS_BUCKET_NAME
    region: us-east-1
notifications:
  email: false
